const teams = {
  "Айнтрахт Франкфурт": "Eintracht_Frankfurt",
  Аякс: "Ajax",
  Арсенал: "Arsenal",
  "Астон Вилла": "Aston_Villa",
  Аталанта: "Atalanta",
  "Атлетик Бильбао": "Athletic_Bilbao",
  Атлетико: "Atletico",
  Байер: "Bayer",
  Бавария: "Bayern",
  Барселона: "Barcelona",
  Бенфика: "Benfica",
  Бернли: "Burnley",
  Бетис: "Betis",
  Болонья: "Bologna",
  Борнмут: "Bournemouth",
  "Борнмут/Манчестер Сити": "Manchester_City",
  "Боруссия Дортмунд": "Borussia_Dortmund",
  Брайтон: "Brighton",
  Брентфорд: "Brentford",
  "Буде-Глимт": "Bodo_Glimt",
  Брюгге: "Brugge",
  Валенсия: "Valencia",
  Верона: "Verona",
  "Вест Хэм": "West_Ham",
  Вильярреал: "Villarreal",
  Вулверхэмптон: "Wolverhampton",
  Галатасарай: "Galatasaray",
  "Депортиво Алавес": "Deportivo_Alaves",
  Дженоа: "Genoa",
  Жирона: "Girona",
  Интер: "Inter",
  Кальяри: "Cagliari",
  Карабах: "Qarabag",
  Кайрат: "Kairat",
  Комо: "Como",
  Копенгаген: "Copenhagen",
  Кремонезе: "Cremonese",
  "Кристал Пэлас": "Crystal_Palace",
  "Кристал Пэлас/Манчестер Сити": "Manchester_City",
  Лацио: "Lazio",
  Леванте: "Levante",
  Лечче: "Lecce",
  Ливерпуль: "Liverpool",
  Лидс: "Leeds",
  Мальорка: "Mallorca",
  "Манчестер Сити": "Manchester_City",
  "Манчестер Юнайтед": "Manchester_United",
  Марсель: "Marseille",
  Милан: "Milan",
  Монако: "Monaco",
  Наполи: "Napoli",
  "Ноттингем Форест": "Nottingham_Forest",
  Ньюкасл: "Newcastle",
  Олимпиакос: "Olympiacos",
  Осасуна: "Osasuna",
  Парма: "Parma",
  Пафос: "Pafos",
  Пиза: "Pisa",
  ПСВ: "PSV",
  ПСЖ: "PSG",
  "Райо Вальекано": "Rayo_Vallecano",
  "Реал Мадрид": "Real_Madrid",
  "Реал Овьедо": "Real_Oviedo",
  "Реал Сосьедад": "Real_Sociedad",
  Рома: "Roma",
  Сандерленд: "Sunderland",
  Сассуоло: "Sassuolo",
  Севилья: "Sevilla",
  Сельта: "Celta",
  Славия: "Slavia",
  Спортинг: "Sporting",
  Торино: "Torino",
  Тоттенхэм: "Tottenham",
  Удинезе: "Udinese",
  Фиорентина: "Fiorentina",
  Фулхэм: "Fulham",
  Хетафе: "Getafe",
  Челси: "Chelsea",
  Эвертон: "Everton",
  Эльче: "Elche",
  Эспаньол: "Espanyol",
  Ювентус: "Juventus",
  Юнион: "Union",
}; // Логотипы команд